import {
  IconBook2,
  IconDashboard,
  IconHeart,
  IconMoneybag,
  IconUser,
  IconUserCircle,
  IconUsersGroup,
} from '@tabler/icons-react';

export const coursesArray = [
  {
    id: 1,
    img: 'https://themes.stackbros.in/eduport_r/assets/08-DgNLqCM_.jpg',
    title: 'Sketch from A to Z: for app designer',
    level: 'All level',
    description: 'Proposal indulged no do sociable he throwing settling.',
    rating: 4,
    duration: '12h 56m',
    numberOfLectures: 12,
    category: 'Web Design',
  },
  {
    id: 2,
    img: 'https://themes.stackbros.in/eduport_r/assets/02-CLuao9PX.jpg',
    title: 'Graphic Design Masterclass',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Web Design',
  },
  {
    id: 3,
    img: 'https://themes.stackbros.in/eduport_r/assets/03-JifBAStH.jpg',
    title: 'Create a Design System in Figma',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do. Points afraid but may end afraid but...',
    rating: 4.5,
    duration: '5h 56m',
    numberOfLectures: 16,
    category: 'Web Design',
  },
  {
    id: 4,
    img: 'https://themes.stackbros.in/eduport_r/assets/07-dJzvunmQ.jpg',
    title: 'Deep Learning with React-Native',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 8h 56m',
    numberOfLectures: 18,
    category: 'Web Design',
  },
  {
    id: 5,
    img: 'https://themes.stackbros.in/eduport_r/assets/11-CgX7qW4Y.jpg',
    title: 'Build Responsive Websites with HTML',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Web Design',
  },
  {
    id: 6,
    img: 'https://themes.stackbros.in/eduport_r/assets/12-BBA2zDwG.jpg',
    title: 'Graphic Design Masterclass',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Web Design',
  },
  {
    id: 7,
    img: 'https://themes.stackbros.in/eduport_r/assets/04-RS5CBO1g.jpg',
    title: 'Build Websites with CSS',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Web Design',
  },
  {
    id: 8,
    img: 'https://themes.stackbros.in/eduport_r/assets/09-wyx1hhTj.jpg',
    title: 'JavaScript: Full Understanding',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Web Design',
  },
  {
    id: 9,
    img: 'https://themes.stackbros.in/eduport_r/assets/07-dJzvunmQ.jpg',
    title: 'Deep Learning with React-Native',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 8h 56m',
    numberOfLectures: 18,
    category: 'Finance',
  },
  {
    id: 12,
    img: 'https://themes.stackbros.in/eduport_r/assets/08-DgNLqCM_.jpg',
    title: 'Sketch from A to Z: for app designer',
    level: 'All level',
    description: 'Proposal indulged no do sociable he throwing settling.',
    rating: 4,
    duration: '12h 56m',
    numberOfLectures: 12,
    category: 'Development',
  },
  {
    id: 52,
    img: 'https://themes.stackbros.in/eduport_r/assets/11-CgX7qW4Y.jpg',
    title: 'Build Responsive Websites with HTML',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Development',
  },
  {
    id: 64,
    img: 'https://themes.stackbros.in/eduport_r/assets/12-BBA2zDwG.jpg',
    title: 'Graphic Design Masterclass',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Development',
  },
  {
    id: 33,
    img: 'https://themes.stackbros.in/eduport_r/assets/03-JifBAStH.jpg',
    title: 'Create a Design System in Figma',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do. Points afraid but may end afraid but...',
    rating: 4.5,
    duration: '5h 56m',
    numberOfLectures: 16,
    category: 'Marketing',
  },
  {
    id: 8,
    img: 'https://themes.stackbros.in/eduport_r/assets/09-wyx1hhTj.jpg',
    title: 'JavaScript: Full Understanding',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Marketing',
  },
  {
    id: 23,
    img: 'https://themes.stackbros.in/eduport_r/assets/02-CLuao9PX.jpg',
    title: 'Graphic Design Masterclass',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Graphic Design',
  },
  {
    id: 7,
    img: 'https://themes.stackbros.in/eduport_r/assets/04-RS5CBO1g.jpg',
    title: 'Build Websites with CSS',
    level: 'Beginner',
    description:
      'Rooms oh fully taken by worse do Points afraid but may end Rooms...',
    rating: 4.5,
    duration: ' 9h 56m',
    numberOfLectures: 16,
    category: 'Graphic Design',
  },
];

export const trendingCoursesArray = [
  {
    img: 'https://themes.stackbros.in/eduport_r/assets/15-CA6a5dn-.jpg',
    title: 'Angular - The Complete Guide (2021 Edition)',
    category: 'Development',
    rating: 4.5,
    numberOfLectures: 16,
    duration: '9h 56m',
    price: '15,000',
    level: 'Beginner',
    numberOfRates: 100,
    numberOfStudents: 1000,
    author: 'Larry Lawson',
    authorImage: 'https://themes.stackbros.in/eduport_r/assets/10-BOjYzw86.jpg',
  },
  {
    img: 'https://themes.stackbros.in/eduport_r/assets/16-DaOI1TiK.jpg',
    title: 'Angular - The Complete Guide (2021 Edition)',
    category: 'Development',
    rating: 4.5,
    numberOfLectures: 16,
    duration: '9h 56m',
    price: '15,000',
    level: 'Beginner',
    numberOfRates: 100,
    numberOfStudents: 1000,
    author: 'Larry Lawson',
    authorImage: 'https://themes.stackbros.in/eduport_r/assets/10-BOjYzw86.jpg',
  },
  {
    img: 'https://themes.stackbros.in/eduport_r/assets/17-uYLUGXaP.jpg',
    title: 'Angular - The Complete Guide (2021 Edition)',
    category: 'Development',
    rating: 4.5,
    numberOfLectures: 16,
    duration: '9h 56m',
    price: '15,000',
    level: 'Beginner',
    numberOfRates: 100,
    numberOfStudents: 1000,
    author: 'Lori Stephens',
    authorImage: 'https://themes.stackbros.in/eduport_r/assets/09-1AM4Ze_z.jpg',
  },
  {
    img: 'https://themes.stackbros.in/eduport_r/assets/14-mRx6FUxG.jpg',
    title: 'Angular - The Complete Guide (2021 Edition)',
    category: 'Development',
    rating: 4.5,
    numberOfLectures: 16,
    duration: '9h 56m',
    price: '15,000',
    level: 'Beginner',
    numberOfRates: 100,
    numberOfStudents: 1000,
    author: 'Larry Lawson',
    authorImage: 'https://themes.stackbros.in/eduport_r/assets/10-BOjYzw86.jpg',
  },
  {
    img: 'https://themes.stackbros.in/eduport_r/assets/16-DaOI1TiK.jpg',
    title: 'Angular - The Complete Guide (2021 Edition)',
    category: 'Development',
    rating: 4.5,
    numberOfLectures: 16,
    duration: '9h 56m',
    price: '15,000',
    level: 'Beginner',
    numberOfRates: 100,
    numberOfStudents: 1000,
    author: 'Larry Lawson',
    authorImage: 'https://themes.stackbros.in/eduport_r/assets/10-BOjYzw86.jpg',
  },
];

export const footerLinks = [
  {
    title: 'Company',
    links: [
      { name: 'About', url: '#' },
      { name: 'Blog', url: '#' },
      { name: 'Contact', url: '#' },
    ],
  },
  {
    title: 'Teaching',
    links: [
      { name: 'Become a Teacher', url: '#' },

      { name: 'Terms & Conditions', url: '#' },
    ],
  },
];

export const courses = [
  'Web Design',
  'Development',
  'Graphic Design',
  'Marketing',
  'Finance',
];

export const accountLinks = [
  {
    account: 'Instructor',
    icon: IconUser,
    links: [
      {
        label: 'Dashboard',
        link: '/instructor/dashboard',
        icon: IconDashboard,
      },
      {
        label: 'Courses',
        link: '/instructor/courses',
        icon: IconBook2,
      },
      {
        label: 'Profile',
        link: '/instructor/profile',
        icon: IconUser,
      },
      {
        label: 'Earnings',
        link: '/instructor/earnings',
        icon: IconMoneybag,
      },
      {
        label: 'Students',
        link: '/instructor/students',
        icon: IconUsersGroup,
      },
    ],
  },
  {
    account: 'Student',
    icon: IconUserCircle,
    links: [
      {
        label: 'Dashboard',
        link: '/student/dashboard',
        icon: IconDashboard,
      },
      {
        label: 'Courses',
        link: '/student/courses',
        icon: IconBook2,
      },
      {
        label: 'Wishlist',
        link: '/student/wishlists',
        icon: IconHeart,
      },
      {
        label: 'Profile',
        link: '/student/profile',
        icon: IconUser,
      },
    ],
  },
];
